name: setup-and-test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 16.x
        uses: actions/setup-node@v1
      with:
        node-version: '16'
  - run: make setup
  - run: make test
  - run: make lint