name: setup-and-test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v2
    - uses: action/setup-node@v1
    - run: make install
    - run: make build
    - run: make test
    - run: make lint